/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_patchbuilder_free: (a: number, b: number) => void;
export const patchbuilder_new: () => number;
export const patchbuilder_add_source_chunk: (a: number, b: number, c: number) => void;
export const patchbuilder_finalize_source: (a: number) => void;
export const patchbuilder_set_target_size: (a: number, b: bigint) => void;
export const patchbuilder_add_target_chunk: (a: number, b: number, c: number) => void;
export const patchbuilder_finalize_target: (a: number) => void;
export const patchbuilder_source_size: (a: number) => number;
export const patchbuilder_target_size: (a: number) => number;
export const patchbuilder_are_files_identical: (a: number) => number;
export const patchbuilder_has_output: (a: number) => number;
export const patchbuilder_flush_output: (a: number, b: number) => [number, number];
export const patchbuilder_pending_output_size: (a: number) => number;
export const patchbuilder_reset: (a: number) => void;
export const __wbg_patchapplier_free: (a: number, b: number) => void;
export const patchapplier_new: () => number;
export const patchapplier_add_source_chunk: (a: number, b: number, c: number) => void;
export const patchapplier_set_patch: (a: number, b: number, c: number) => void;
export const patchapplier_source_size: (a: number) => number;
export const patchapplier_validate_source: (a: number) => [number, number, number];
export const patchapplier_expected_source_size: (a: number) => [bigint, number, number];
export const patchapplier_expected_target_size: (a: number) => [bigint, number, number];
export const patchapplier_prepare: (a: number) => [number, number];
export const patchapplier_has_more_output: (a: number) => number;
export const patchapplier_next_output_chunk: (a: number, b: number) => [number, number];
export const patchapplier_remaining_output_size: (a: number) => bigint;
export const patchapplier_reset: (a: number) => void;
export const version: () => [number, number];
export const hash_data: (a: number, b: number) => [number, number];
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
