/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_patchbuilder_free: (a: number, b: number) => void;
export const patchbuilder_new: () => number;
export const patchbuilder_add_source_chunk: (a: number, b: number, c: number) => void;
export const patchbuilder_finalize_source: (a: number) => void;
export const patchbuilder_set_target_size: (a: number, b: bigint) => void;
export const patchbuilder_add_target_chunk: (a: number, b: number, c: number) => void;
export const patchbuilder_finalize_target: (a: number) => void;
export const patchbuilder_source_size: (a: number) => number;
export const patchbuilder_target_size: (a: number) => number;
export const patchbuilder_are_files_identical: (a: number) => number;
export const patchbuilder_has_output: (a: number) => number;
export const patchbuilder_flush_output: (a: number, b: number) => [number, number];
export const patchbuilder_pending_output_size: (a: number) => number;
export const patchbuilder_reset: (a: number) => void;
export const parse_patch_header_only: (a: number, b: number) => [number, number, number, number];
export const version: () => [number, number];
export const __wbg_streaminghasher_free: (a: number, b: number) => void;
export const streaminghasher_new: () => number;
export const streaminghasher_update: (a: number, b: number, c: number) => void;
export const streaminghasher_finalize: (a: number) => [number, number];
export const streaminghasher_finalize_u64: (a: number) => bigint;
export const hash_data: (a: number, b: number) => [number, number];
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
